version: '3.3'

services:

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "nkardj/pbbg-client"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    links:
      - "api:server"

  mysqldb:
    image: mysql
    restart: always
    env_file: .env
    environment:
     - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
     - MYSQL_DATABASE=$DB_NAME
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  api:
    depends_on:
      - mysqldb
    env_file: .env
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "nkardj/pbbg-api"
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_SOCKET_PATH=$SOCKET_PATH

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db-config:
  db-data:

